# Generated by Django 6.0.3 on 2026-03-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='rua',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='escolaridade',
            field=models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('tecnico', 'Técnico'), ('superior', 'Ensino Superior'), ('pos', 'Pós-graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], default='Não informado', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='modelo_trabalho',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='Não informado', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_contrato',
            field=models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estágio'), ('temporario', 'Temporário')], default='Não informado', max_length=20),
            preserve_default=False,
        ),
    ]
