# Generated by Django 6.0.3 on 2026-03-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_remove_funcionario_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='departamento',
            field=models.CharField(choices=[('ti', 'TI'), ('financeiro', 'Financeiro'), ('rh', 'Recursos Humanos'), ('vendas', 'Vendas'), ('marketing', 'Marketing'), ('atendimento', 'Atendimento ao Cliente')], max_length=20),
        ),
    ]
